
opening.bnr: opening.ppm
	../ppm2bnr/ppm2bnr -n "compat bootable disc" -c "OffBoardway" -N "Compat Bootloader Nintendo GameCube" -C "OffBroadway" $< -o $@


clean:
	rm -f \
		*~

dist-clean: clean
	rm -f \
		opening.bnr

dummy:

